[package]
name = "guessing-game"
version = "0.1.0"
edition = "2021"
publish = false

[lib]
crate-type = ["cdylib"]

[dependencies]
rulebook = {path = "../rulebook"}

anyhow = {version = "1.0", features = ["backtrace"]}
serde = {version = "1.0", features = ["derive"]}
